### PR TITLE
Add issue auto-assignment

### PR DESCRIPTION
**Pull request by balanprasanth**
- Added issue auto-assignment script and workflow
- Added auto labels removal if anyone comments.

### CODE REVIEW

**Review by advaitjain — APPROVED** [review]

**Review by advaitjain — APPROVED** [review]

**Comment by balanprasanth** [comment]
Hi @advaitjain , Could you help me to merge this PR? Thank you

**Comment by chunnienc** [comment]
This issue was merged internally yesterday, not sure why the internal merge is not sycned to Github. I'll take a look.

**Comment by chunnienc** [comment]
This PR should be all good and closed by copybara sync. Please don't make further commits here. 

Please send another PR if you need to make changes, thanks!

**Comment by chunnienc** [comment]
Sync is fixed now. All in this PR are merged in https://github.com/google-ai-edge/ai-edge-torch/tree/main/.github/workflows

**Pull request closed without merging**
